#ifndef PROFILE_INCLUDE_H
#define PROFILE_INCLUDE_H

#include "gostreamsystem.h"
#include "colorbacks.h"
#include "colorback.h"
#include "mixeffectblocks.h"
#include "mixeffectblock.h"
#include "program.h"
#include "preview.h"
#include "nexttransition.h"
#include "mixparameters.h"
#include "dipparameters.h"
#include "wipeparameters.h"
#include "transitionstyle.h"
#include "lumaparameters.h"
#include "chromaparameters.h"
#include "patternparameters.h"
#include "pipparameters.h"
#include "keys.h"
#include "key.h"
#include "fadetoblack.h"
#include "downstreamkeys.h"
#include "downstreamkey.h"
#include "supersources.h"
#include "supersource.h"
#include "supersourceborder.h"
#include "supersourcemask.h"
#include "audiomixer.h"
#include "audioinput.h"
#include "audiooutput.h"
#include "audiosource.h"
#include "stillgenerator.h"
#include "still.h"
#include "stills.h"
#include "stillselection.h"

#endif // PROFILE_INCLUDE_H
